# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription_service/transcription_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1transcription_service/transcription_service.proto\x12\rtranscription\"\\\n\x14TranscriptionRequest\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x1c\n\x14\x61udio_directory_path\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\"I\n\x15TranscriptionResponse\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x1c\n\x14\x61udio_directory_path\x18\x02 \x01(\t2t\n\x14TranscriptionService\x12\\\n\x0fTranscribeAudio\x12#.transcription.TranscriptionRequest\x1a$.transcription.TranscriptionResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_service.transcription_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSCRIPTIONREQUEST._serialized_start=68
  _TRANSCRIPTIONREQUEST._serialized_end=160
  _TRANSCRIPTIONRESPONSE._serialized_start=162
  _TRANSCRIPTIONRESPONSE._serialized_end=235
  _TRANSCRIPTIONSERVICE._serialized_start=237
  _TRANSCRIPTIONSERVICE._serialized_end=353
# @@protoc_insertion_point(module_scope)
