# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from transcription_service import transcription_service_pb2 as transcription__service_dot_transcription__service__pb2


class TranscriptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeAudio = channel.unary_unary(
                '/transcription.TranscriptionService/TranscribeAudio',
                request_serializer=transcription__service_dot_transcription__service__pb2.TranscriptionRequest.SerializeToString,
                response_deserializer=transcription__service_dot_transcription__service__pb2.TranscriptionResponse.FromString,
                )


class TranscriptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=transcription__service_dot_transcription__service__pb2.TranscriptionRequest.FromString,
                    response_serializer=transcription__service_dot_transcription__service__pb2.TranscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transcription.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transcription.TranscriptionService/TranscribeAudio',
            transcription__service_dot_transcription__service__pb2.TranscriptionRequest.SerializeToString,
            transcription__service_dot_transcription__service__pb2.TranscriptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
